# Generated by Django 4.2.2 on 2023-08-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("basicapp", "0002_uploadimage_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInformation",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("contact", models.PositiveIntegerField()),
                ("profile_image", models.ImageField(upload_to="profile_pictures/")),
            ],
        ),
    ]
